### ISSUE TITLE
Update content on staging site

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#414]
Prior to launch, we will need to ensure all content is up-to-date and accurate. This includes:
- [x] Up-to-date directory
- [x] Sensible directory taxonomy (avoid "All, All" type labels)
- [x] Up-to-date release information (#427)
- [X] All prior blog posts imported
  - no link breakage, except for the blog URL listed on #437 and tracked separately
- [X] All GPG keys up-to-date
 - Release signing key updated. Unfortunately it will 404 until the new site is live, since that particular field requires an absolute URL.
  - We no longer reference securedrop@ - should we?
- [X] Privacy policy (just link to FPF policy?)
  - linked to FPF policy for now, FPF policy could use some tweaking to make it clear that it applies to more than one site
- [X] Sample privacy policy for SD instances [linked to docs version instead of keeping a copy]
- [X] FAQs complete and up-to-date [landing page reformatted, all content reviewed, some sections updated, all links checked]
- [X] Static files uploaded as documents (list in #432)
  - [X] Audit reports uploaded
  - [X] Signing key and email key uploaded and redirects from old paths requested in #432 
  - [X] Images in blog posts uploaded (most were already done)
- [x] Update navigational links (see https://github.com/freedomofpress/securedrop.org/issues/403)
- [X] Fix or remove "Media" link
  - removed for now
- [X] Create "Get support" page
 - Added a "Priority Support" page: https://staging.securedrop.org/priority-support/
- [x] Cleanup of devdata and other remnants from staging (see https://github.com/freedomofpress/securedrop.org/issues/387)
