### ISSUE TITLE
Integrate source interface + landing page scan results in directory

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop.org#488]
This is an epic to work towards an integration of source interface and landing page scan results in the SecureDrop directory as described [here](https://docs.google.com/document/d/1ySA40iQVTWyKobU2sZemC9H9sODUYQZ5G8WvhpTBmMc/edit#). Details of the epic will evolve as this discussion continues, and we will add tasks below as appropriate.

Lower priority improvements to scan results that can be completed after the launch of the initial integration are *not* part of this epic. These types of landing page page scanner improvements are tracked through [this label](https://github.com/freedomofpress/securedrop.org/labels/landing%20page%20scanner).

### Preparatory:
- [x] Finalize icon set for directory badges - #489 
- [x] Check the plan below against a threat model for landing pages - #512
- [x] Enable the landing page scanner and collect baseline scan data - #518 

### Delisting logic:
- [x] Support "delisted" state for individual directory entries - #491
- [ ] Automatically delist instances with major landing page HTTPS issues - #492
- [ ] Automatically delist instances with landing pages served with non-200 HTTP status - #493

### Pre-launch scanner improvements:
- [x] Support landing page redirects on the same domain - #494
- [x] Check for assets on third party domain - #506 (may choose to defer)
- [x] Add support for Referrer-Policy header - #515

### Warning logic:
- [x] Add support for "moderate" and "severe" warnings on directory entry pages - #514
- [x] Create per-request flag for showing warnings about landing page issues - #498
- [x] Show severe warning on directory entry page for entries with third party assets or analytics scripts - #496
- [x] Show moderate warning on directory entry page for landing pages hosted on subdomain - #497
- [x] Show moderate warning on directory entry page for landing pages without Referrer Policy - #516
- [x] Show moderate warning on directory entry page for landing pages with links to .onion addresses  - #517

### Deployment:
- [x] Give news organizations time to address landing page issues - #499
- [ ] Make warning display the default - #500 

## Phase 2: Source interface support

- [ ] Associate source interface scan results with directory entries - #501
- [ ] Display SecureDrop version on directory entry - #502
- [ ] Display "Unreachable" icon and SecureDrop downtime - #503
- [ ] Automatically delist instances with extended downtime - #504
